services:
  - type: web
    name: xibot-v12
    runtime: node
    buildCommand: npm install
    startCommand: node bot-v12.js .env.bot1
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: BOT_ID
        value: bot1
      - key: BOT_VERSION
        value: v12
      - key: BOT_FILE
        value: bot-v12.js
      - key: ENV_FILE
        value: .env.bot1 