services:
  - type: web
    name: xin-bot1
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: BOT_ID
        value: bot1
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    plan: free
    scaling:
      minInstances: 1
      maxInstances: 1

  - type: web
    name: xin-bot2
    runtime: node
    buildCommand: npm install
    startCommand: npm run start:bot2
    envVars:
      - key: PORT
        value: 3001
      - key: BOT_ID
        value: bot2
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    plan: free
    scaling:
      minInstances: 1
      maxInstances: 1 